// input buttons selector
const inputTotalNumber = document.querySelector("#input-total-amount");
const btn5 = document.querySelector(".btn-5");
const btn10 = document.querySelector(".btn-10");
const btn15 = document.querySelector(".btn-15");
const btn25 = document.querySelector(".btn-25");
const btn50 = document.querySelector(".btn-50");
const btnCustom = document.querySelector(".btn-custom");
const tipBtns = document.querySelector(".btn-tip");
const totalPeople = document.querySelector("#input-total-people");